version: '3'

services:
  ca-base:
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    platform: ${DOCKER_DEFAULT_PLATFORM}
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
      - FABRIC_CA_SERVER_CA_NAME=
      - FABRIC_CA_SERVER_CSR_HOSTS=
    networks:
      - net

  orderer-base:
    image: hyperledger/fabric-orderer:${FABRIC_ORDERER_VERSION}
    platform: ${DOCKER_DEFAULT_PLATFORM}
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=Org0MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/tmp/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/tmp/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/tmp/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/tmp/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/tmp/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/tmp/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/tmp/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9443
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:9444
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - /tmp/hyperledger/config:/tmp/hyperledger/config
    networks:
      - net

  couchdb-base:
    image: couchdb:${COUCHDB_VERSION}
    platform: ${DOCKER_DEFAULT_PLATFORM}
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin-pw
    networks:
      - net

  peer-base:
    image: hyperledger/fabric-peer:${FABRIC_PEER_VERSION}
    platform: ${DOCKER_DEFAULT_PLATFORM}
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${DOCKER_NETWORK_NAME}
      # - FABRIC_CFG_PATH=/tmp/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=
      - CORE_PEER_ADDRESS=
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=
      - CORE_PEER_LOCALMSPID=
      - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG=
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin-pw
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
    networks:
      - net

  cli-base:
    image: hyperledger/fabric-tools:${FABRIC_TOOLS_VERSION}
    platform: ${DOCKER_DEFAULT_PLATFORM}
    tty: true
    volumes:
      - ${SCRIPT_DIR}/config:/tmp/hyperledger/config
    networks:
      - net
